// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRaCKkX0mAPcqPe4BqVON0oW30eJGEZlg',
    appId: '1:54724475146:android:b33fafff3e56ee5d6de2f3',
    messagingSenderId: '54724475146',
    projectId: 'fir-todo-282bc',
    storageBucket: 'fir-todo-282bc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByp4Sr9ZYarHsrnb17sa78MlrY_fc4t8s',
    appId: '1:54724475146:ios:ba62576a88ed9a5b6de2f3',
    messagingSenderId: '54724475146',
    projectId: 'fir-todo-282bc',
    storageBucket: 'fir-todo-282bc.firebasestorage.app',
    iosClientId: '54724475146-uvcdhcflmtpaheh78rc3822cbjovc44n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpjllGQFWnfap9q0Ocaz0pMi4tPXL3I8',
    appId: '1:54724475146:web:b9388011d2c721366de2f3',
    messagingSenderId: '54724475146',
    projectId: 'fir-todo-282bc',
    authDomain: 'fir-todo-282bc.firebaseapp.com',
    storageBucket: 'fir-todo-282bc.firebasestorage.app',
  );
}
